language: php
os: linux
dist: bionic

php:
  - 7.2
  - 7.3
  - 7.4

# Use a recent version of npm. Local dependencies don't work on the Travis default npm.
node_js:
  - 11

git:
  depth: false

env:
  global:
    - DRUPAL_TEST_DB_URL=sqlite://localhost/sites/default/files/test.sqlite
    - SIMPLETEST_DB=sqlite://localhost/sites/default/files/test.sqlite
    - DRUPAL_TEST_BASE_URL=http://localhost:8888
    - TRAVIS=true
    - DRUPAL_VERSION=8.8.5
    - DRUPAL_BUILD_DIR=$(realpath $TRAVIS_BUILD_DIR/../drupal-$DRUPAL_VERSION)
    - PATH=$PATH:$DRUPAL_BUILD_DIR/vendor/bin
    - MODULE_NAME=delivery
    - LOGS_DIR=$DRUPAL_BUILD_DIR/build/logs
    - REPO_BRANCH=$TRAVIS_BRANCH

# Cache composer downloads.
cache:
  directories:
    - $HOME/.composer
    - $DRUPAL_BUILD_DIR/drupal-$MODULE_NAME-environment/node_modules
    - $HOME/.cache/$MODULE_NAME

before_install:
  # If this is a PR, we want to check out the PR branch.
  - if [ ! "$TRAVIS_PULL_REQUEST" = "false" ]; then REPO_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH; fi
  # Travis does a checkout on a specific commit that prevents using local repos.
  - git checkout -qf $REPO_BRANCH
  # Composer setup.
  - COMPOSER_MEMORY_LIMIT=-1 composer self-update
  # Download and unpack Drupal.
  - curl -O https://ftp.drupal.org/files/projects/drupal-$DRUPAL_VERSION.tar.gz
  - tar -xf drupal-$DRUPAL_VERSION.tar.gz -C $TRAVIS_BUILD_DIR/../

install:
  - cd $DRUPAL_BUILD_DIR
  # Force Composer to use our version of the module.
  - php -r "\$json = json_decode(file_get_contents('composer.json'), TRUE); \$json['repositories'][] = ['type' => 'vcs', 'url' => '$TRAVIS_BUILD_DIR' ]; \$json['extra']['enable-patching'] = TRUE; file_put_contents('composer.json', json_encode(\$json, JSON_PRETTY_PRINT));"
  # Install Composer Patches.
  - COMPOSER_MEMORY_LIMIT=-1 composer --working-dir=$DRUPAL_BUILD_DIR require cweagans/composer-patches
  # Install Drush.
  - COMPOSER_MEMORY_LIMIT=-1 composer --working-dir=$DRUPAL_BUILD_DIR require drush/drush:^10 alchemy/zippy
  # Upgrade phpunit to work with PHP 7.
  - COMPOSER_MEMORY_LIMIT=-1 composer --working-dir=$DRUPAL_BUILD_DIR require phpunit/phpunit:^7 symfony/phpunit-bridge phpspec/prophecy sebastian/global-state:^2 sebastian/environment:^3.1 phpunit/php-code-coverage:^6 mikey179/vfsstream
  # Install static analysis tools.
  - COMPOSER_MEMORY_LIMIT=-1 composer --working-dir=$DRUPAL_BUILD_DIR require phpstan/phpstan phpstan/extension-installer mglaman/phpstan-drupal phpstan/phpstan-deprecation-rules
  # Install Coveralls integration.
  - COMPOSER_MEMORY_LIMIT=-1 composer --working-dir=$DRUPAL_BUILD_DIR require php-coveralls/php-coveralls

script:
  # Logs.
  - mkdir -p $LOGS_DIR
  # Get the module.
  - COMPOSER_MEMORY_LIMIT=-1 composer require "drupal/$MODULE_NAME"
  # Do a minimal Drupal installation. Required for Drush.
  - php core/scripts/drupal install -q minimal
  # Run a simple HTTP server on port 8888.
  - ./vendor/bin/drush serve -q &
  # Analyse code.
  - ./vendor/bin/phpstan analyse $TRAVIS_BUILD_DIR || true
  # Copy our custom PHPUnit config file to ensure paths are correct.
  - cp $TRAVIS_BUILD_DIR/phpunit.xml.dist $DRUPAL_BUILD_DIR/core/phpunit.xml
  # Run Drupal Unit tests in this module.
  - ./vendor/bin/phpunit -c core/phpunit.xml $TRAVIS_BUILD_DIR --coverage-clover $LOGS_DIR/clover.xml --whitelist $TRAVIS_BUILD_DIR

after_success:
  # Send coverage data to coveralls.
  - cd $TRAVIS_BUILD_DIR
  - travis_retry php $DRUPAL_BUILD_DIR/vendor/bin/php-coveralls -vvv --root_dir $DRUPAL_BUILD_DIR
