field.field.*.*.*.third_party.delivery:
  type: mapping
  label: 'Conflict field settings'
  mapping:
    blacklisted:
      type: boolean
      label: 'Exclude field from being merged'

action.configuration.delivery_add_to_cart_action:
  type: action_configuration_default
  label: 'Add to the delivery cart'
